# Hold ourselves to a high bar
coverage:
  range: 85..100
  round: down
  precision: 1
  status:
    project:
      default:
        threshold: 1%

# Test files aren't important for coverage
ignore:
  - "tests"

# Make less noisy comments
comment:
  layout: "files"
  require_changes: yes
