on:
  push:
    branches: [master]
  pull_request:
name: cargo hack
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install cargo-hack
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-hack
          version: latest
          use-tool-cache: true
      - name: cargo hack
        uses: actions-rs/cargo@v1
        with:
          command: hack
          args: --feature-powerset check
