on:
  push:
    branches: [master]
  pull_request:
name: cargo test
jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} / ${{ matrix.toolchain }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolchain: [stable]
        include:
          - os: ubuntu-latest
            toolchain: beta
          - os: ubuntu-latest
            toolchain: nightly
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
      - uses: actions/checkout@v2
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
